# Generated by Django 4.1.7 on 2023-03-25 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=8)),
                ('logo_upload', models.ImageField(upload_to='logos/')),
                ('location', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('choose_field', models.CharField(choices=[('field1', 'Field 1'), ('field2', 'Field 2'), ('field3', 'Field 3')], max_length=20)),
            ],
        ),
    ]
