# Generated by Django 4.1.7 on 2023-03-25 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='choose_field',
            field=models.CharField(choices=[('Design & creative', 'Design & creative'), ('Design & development', 'Design & creative'), ('sales & marketing', 'sales & marketing'), ('mobile Application', 'mobile Application'), ('construction', 'construction'), ('Information technology', 'Information technology')], max_length=200),
        ),
    ]
