# Generated by Django 4.1.7 on 2023-03-26 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_job_choose_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('answer_1', models.CharField(max_length=200)),
                ('answer_2', models.CharField(max_length=200)),
                ('answer_3', models.CharField(max_length=200)),
                ('answer', models.CharField(max_length=200)),
                ('choose_field', models.CharField(choices=[('Design & creative', 'Design & creative'), ('Design & development', 'Design & development'), ('sales & marketing', 'sales & marketing'), ('mobile Application', 'mobile Application'), ('construction', 'construction'), ('Information technology', 'Information technology')], default='default_value', max_length=200)),
            ],
        ),
    ]
